### ISSUE TITLE
arrays for array jobs are 0 based

### ISSUE THREAD

**Issue by lmavila** [RILAB/lab-docs#2]
in the example, the array job is specified in this way
#SBATCH --array=1-9

bob=( 1 1 1 2 2 2 3 3 3 )
sue=( 1 2 3 1 2 3 1 2 3 )
from my tests it appears that "#SBATCH --array=0-8" should be used in this example otherwise the first element of the bob and sue arrays (element 0) would not be used.

**Comment by rossibarra** [comment]
good catch. zsh is 1-based!
