### ISSUE TITLE
which node to use for data transfer

### ISSUE THREAD

**Issue by rossibarra** [RILAB/lab-docs#5]
which node to use for rsync, iplant transfer, etc. and instructions how to do so.

**Comment by wenbinmei** [comment]
Farm cluster has a dedicated port (-p 2022) to transfer the big data such as rsync, wget, iplant transfer et al. This way you can avoid messing up the farm head node, which would slow down everyone using the farm cluster.

If you follow Jeff's lab farm documents to set up your farm log in. You need to type following to log into port 2022: ssh -p 2022 farm

After you log into the farm cluster, you can type "screen" command in your terminal, afterwards press "Return" to start. Now you can type you favorite wget/rsync command to download/transfer the data. When you wget/rsync command starts, type "control+A+Z" it would put your screen working in the background. If you want to resume your screen, type "screen -list" it would list all your screen working in the background and you will see the list of screen as below. 

There is a screen on:
	19385.pts-0.c8-25	(12/22/2016 12:31:13 PM)	(Detached)
 
Now if you want to resume to one of the screen working in the background, type "screen -r 19385.pts-0.c8-25" it would go back your previous wget/rsync command.  If you want to exit the screen, then type "exit".

Now many people store the raw data on the iplant. If you want to download the data from iplant, be careful sometimes the connection would break before you finish uploading or downloading the files, and you can use below to avoid the problem (at least working for me):

iget -K -P -T --retries 3 --lfrestart checkpoint-file path_to_your_file

If you want to upload all the files in the fold to the iplant, you can use below command:

iput -K -P -b -f -r -T --retries 3 -X checkpoint_file upload_path_fold location_iplant_upload

If you want to download many things, you can put multiple iput and iget command in a bash script. You can use command below to document the process of upload or download.

sh bash_script_upload_download_iplant.sh | tee -a record_download_upload_progress.txt

In the file record_download_upload_progress.txt you can see how many percentage of your files have been upload or download to the iplant.

Farm is a great cluster as long as you treat it nicely, and in return farm would do great things for your research, enjoy the farm cluster!
